spring.application.name=bff-service
server.port=8080
management.endpoints.web.exposure.include=health,info
app.services.cursos-url=${CURSOS_SERVICE_URL:http://localhost:8081}
app.services.inscripciones-url=${INSCRIPCIONES_SERVICE_URL:http://localhost:8082}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://tenant-ficticio.b2clogin.com/tenant-id/v2.0/}
app.security.jwk-set-uri=${AZURE_JWK_SET_URI:https://tenant-ficticio.b2clogin.com/tenant.onmicrosoft.com/B2C_1_flujo/discovery/v2.0/keys}
app.security.audience=${AZURE_CLIENT_ID:00000000-0000-0000-0000-000000000000}
app.security.roles-claim=${AZURE_ROLES_CLAIM:extension_RolGuia}
app.security.demo-enabled=${APP_SECURITY_DEMO_ENABLED:false}
app.cors.allowed-origin=${FRONTEND_ALLOWED_ORIGIN:http://localhost:5173}
