spring.application.name=cursos-service
server.port=8081
spring.datasource.url=${DB_URL:jdbc:h2:mem:cursos;DB_CLOSE_DELAY=-1}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
app.aws.region=${AWS_REGION:us-east-1}
app.aws.s3.bucket=${AWS_S3_BUCKET:eft-cursos-materiales-demo}
app.aws.s3.upload-enabled=${AWS_S3_UPLOAD_ENABLED:false}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://tenant-ficticio.b2clogin.com/tenant-id/v2.0/}
app.security.jwk-set-uri=${AZURE_JWK_SET_URI:https://tenant-ficticio.b2clogin.com/tenant.onmicrosoft.com/B2C_1_flujo/discovery/v2.0/keys}
app.security.audience=${AZURE_CLIENT_ID:00000000-0000-0000-0000-000000000000}
app.security.roles-claim=${AZURE_ROLES_CLAIM:extension_RolGuia}

